import test from 'node:test';
import assert from 'node:assert/strict';
import { cleanupReason, patchSingleton, readOwnedRecord, readSingletonRows, repairOwnedAssetMime } from '../../dev/storefront-acceptance.mjs';
import {
  LOCAL_URL, appendOwnedId, assertLocalTarget, casApplyPatch, casRestorePatch, directusRows,
  collectionEndpoint, createFixturePlan, guardedDeleteRequest, makeOwnershipManifest, productAnalogKey, readCollectionRows, reconcileLegacySectionPage, redactSummary, serviceEmailForRun,
  safeManifestDirectory,
} from '../../dev/storefront-acceptance-fixtures.mjs';

const id = '7a7a7a7a-7a7a-47a7-87a7-7a7a7a7a7a7a';

test('only the exact approved loopback Directus URL is accepted', () => {
  assert.equal(assertLocalTarget(LOCAL_URL), LOCAL_URL);
  for (const value of ['http://localhost:18056', 'http://127.0.0.1:18056/admin', 'https://127.0.0.1:18056', 'http://127.0.0.1:18057', 'http://admin@127.0.0.1:18056']) {
    assert.throws(() => assertLocalTarget(value), /exactly http/u);
  }
});

test('system collection reads use supported native endpoints with Directus query shape', async () => {
  const calls = [];
  const client = { request: async path => { calls.push(path); return []; } };
  for (const collection of ['directus_folders', 'directus_files', 'directus_users', 'directus_roles', 'directus_policies', 'directus_access']) await readCollectionRows(client, collection, new URLSearchParams({ 'filter[id][_eq]': id, limit: '1', fields: 'id' }));
  assert.deepEqual(calls.map(path => path.split('?')[0]), ['/folders', '/files', '/users', '/roles', '/policies', '/access']);
  assert.equal(collectionEndpoint('products'), '/items/products');
  assert.ok(calls.every(path => path.includes('filter%5Bid%5D%5B_eq%5D=') && path.includes('fields=id')));
});

test('singleton reads accept Directus object payloads and retain array compatibility', () => {
  const singleton = { id, status: 'published' };
  assert.deepEqual(directusRows(singleton), [singleton]);
  assert.deepEqual(directusRows([singleton]), [singleton]);
  assert.deepEqual(directusRows(null), []);
});

test('singleton read and patch use collection-level Directus routes', async () => {
  const calls = [];
  const client = { request: async (path, options) => { calls.push({ path, options }); return { id, status: 'draft' }; } };
  const rows = await readSingletonRows(client, 'home_page', ['id', 'status']);
  assert.deepEqual(rows, [{ id, status: 'draft' }]);
  await patchSingleton(client, 'home_page', { status: 'published' });
  assert.equal(calls[0].path, '/items/home_page?fields=id%2Cstatus&limit=1');
  assert.equal(calls[1].path, '/items/home_page');
  assert.equal(calls[1].options.method, 'PATCH');
  assert.deepEqual(JSON.parse(calls[1].options.body), { status: 'published' });
  assert.throws(() => patchSingleton(client, 'products', { status: 'draft' }), /Unsupported/u);
});

test('home singleton ownership uses exact item reads and only treats confirmed 404 as absent', async () => {
  const calls = [], client = { request: async path => { calls.push(path); return { id, status: 'published' }; } };
  assert.deepEqual(await readOwnedRecord(client, 'home_page', id), { id, status: 'published' });
  assert.equal(calls[0], `/items/home_page/${id}`);
  assert.equal(await readOwnedRecord({ request: async () => { throw Error('HTTP 404 missing'); } }, 'home_page', id), null);
  await assert.rejects(readOwnedRecord({ request: async () => { throw Error('HTTP 403 denied'); } }, 'home_page', id), /HTTP 403/u);
});

test('owned file MIME repair requires exact ownership and byte-identical generated content', async () => {
  const id = '8b8b8b8b-8b8b-48b8-88b8-8b8b8b8b8b8b';
  const filename = 'fixture-public-12345678.pdf';
  const bytes = Buffer.from('%PDF-1.4\n1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n2 0 obj<< /Type /Pages /Kids [] /Count 0 >>endobj\ntrailer<< /Root 1 0 R >>\n%%EOF\n');
  const manifest = { created: { directus_files: [id] }, ownership: { directus_files: { [id]: { id, folder: 'folder-id', filename_download: filename } } } };
  const calls = [];
  const client = { baseUrl: LOCAL_URL, token: 'hidden', request: async path => {
    calls.push(path);
    return [{ id, folder: 'folder-id', filename_download: filename, type: 'application/octet-stream' }];
  } };
  const fetchImpl = async (url, options = {}) => {
    calls.push([url, options.method ?? 'GET']);
    if (url.endsWith(`/assets/${id}`)) return { ok: true, arrayBuffer: async () => bytes };
    return { ok: true, json: async () => ({ data: { id, type: 'application/pdf' } }) };
  };
  await repairOwnedAssetMime(client, manifest, fetchImpl);
  assert.equal(manifest.ownership.directus_files[id].type, 'application/pdf');
  assert.deepEqual(calls.slice(1), [[`${LOCAL_URL}/assets/${id}`, 'GET'], [`${LOCAL_URL}/files/${id}`, 'PATCH']]);
});

test('owned file MIME repair refuses replacement if generated bytes do not match', async () => {
  const id = '8b8b8b8b-8b8b-48b8-88b8-8b8b8b8b8b8b';
  const filename = 'fixture-public-12345678.pdf';
  const manifest = { created: { directus_files: [id] }, ownership: { directus_files: { [id]: { id, folder: 'folder-id', filename_download: filename } } } };
  const client = { baseUrl: LOCAL_URL, token: 'hidden', request: async () => [{ id, folder: 'folder-id', filename_download: filename, type: 'application/octet-stream' }] };
  let patched = false;
  const fetchImpl = async url => {
    if (url.endsWith(`/assets/${id}`)) return { ok: true, arrayBuffer: async () => Buffer.from('other bytes') };
    patched = true; return { ok: true, json: async () => ({ data: { id, type: 'application/pdf' } }) };
  };
  await assert.rejects(repairOwnedAssetMime(client, manifest, fetchImpl), /bytes differ/u);
  assert.equal(patched, false);
});

test('synthetic fixture plan covers the required public, variant, pricing, stock and draft cases', () => {
  const plan = createFixturePlan({ runId: id });
  assert.equal(plan.products.length, 15);
  assert.equal(new Set(plan.categories.map(row => row.slug)).size, 3);
  assert.equal(new Set(plan.products.map(row => row.brand)).size, 3);
  assert.ok(plan.products.some(row => row.sku.includes('LONG-SKU')));
  assert.ok(plan.products.some(row => row.title.length > 150));
  assert.deepEqual(new Set(plan.products.map(row => row.price_status)), new Set(['fixed', 'on_request', 'hidden']));
  assert.deepEqual(new Set(plan.products.map(row => row.availability_status)), new Set(['in_stock', 'on_request', 'out_of_stock']));
  assert.equal(plan.products.at(-1).is_indexable, false);
  assert.equal(plan.drafts.length, 2);
  assert.ok(plan.children.every(row => row.specification.status === 'draft' && row.image.image));
  assert.equal(plan.children[0].image.status, 'published');
  assert.equal(plan.children[1].image.status, 'draft');
  assert.ok(plan.products.every(row => row.mpn.startsWith('MPN-FX-')));
  assert.ok(plan.products.some(row => row.gallery && row.specifications && row.documents));
  assert.deepEqual(plan.assets, ['fixture-gallery.png', 'fixture-home.png', 'fixture-draft-only.png', 'fixture-unreferenced.png', 'fixture-document.html', 'fixture-public.pdf', 'fixture-private.pdf']);
});

test('manifest ownership is exact, UUID-only, and summaries redact identifiers', () => {
  const manifest = makeOwnershipManifest(id);
  appendOwnedId(manifest, 'products', id);
  appendOwnedId(manifest, 'products', id);
  assert.deepEqual(manifest.created.products, [id]);
  assert.throws(() => appendOwnedId(manifest, 'products', 'baseline-row'), /invalid ownership/u);
  assert.deepEqual(redactSummary({ ...manifest, service: { userId: id, token: 'secret' } }), {
    status: 'planned', counts: { ...Object.fromEntries(Object.keys(manifest.created).map(key => [key, 0])), products: 1 }, childCreateVerified: false, sectionCreateVerified: null, sectionProbeStatus: null, serviceConfigured: false,
  });
  manifest.phase = 'active';
  manifest.created.directus_users.push(id);
  assert.equal(redactSummary({ ...manifest, service: { userId: id, token: 'secret' } }).serviceConfigured, true);
  assert.match(serviceEmailForRun(id), /^[a-z0-9-]+@example\.com$/u);
  assert.match(safeManifestDirectory('D:/site-copy'), /[\\/]dev[\\/]\.storefront-acceptance$/u);
});

test('live fixture workflow gates child writes on verified native REST probes', () => {
  // Controlled local probes confirmed nested product specifications and a
  // standalone page_sections POST through exact REST readbacks.
  const manifest = makeOwnershipManifest(id);
  assert.equal(manifest.childCreateVerified, false);
  assert.equal(manifest.sectionCreateVerified, null);
  manifest.childCreateVerified = true;
  manifest.sectionCreateVerified = true;
  manifest.sectionProbeOutcome = { status: 'verified', httpStatus: null, code: null };
  const summary = redactSummary(manifest);
  assert.equal(summary.childCreateVerified, true);
  assert.equal(summary.sectionCreateVerified, true);
  assert.equal(summary.sectionProbeStatus, 'verified');
  assert.equal(Object.hasOwn(summary, 'namedRefs'), false);
});

test('CAS restore allows original or fixture state and refuses third-party changes', () => {
  const snapshot = { commerce_profile: { currency: 'RUB', features: { cart: false, parts_request: false } }, title: 'old' };
  const original = { ...snapshot };
  const fixture = { ...snapshot, commerce_profile: { currency: 'RUB', features: { cart: false, parts_request: true } } };
  assert.deepEqual(casRestorePatch(snapshot, original, ['commerce_profile'], fixture), {});
  assert.deepEqual(casRestorePatch(snapshot, fixture, ['commerce_profile'], fixture), { commerce_profile: snapshot.commerce_profile });
  assert.throws(() => casRestorePatch(snapshot, { ...snapshot, commerce_profile: { currency: 'USD', features: { cart: true, parts_request: true } } }, ['commerce_profile'], fixture), /changed after/u);
});

test('CAS resume applies only original fields and accepts already-fixtured fields', () => {
  const original = { parts_request: false, cart: false }, expected = { parts_request: true, cart: false };
  assert.deepEqual(casApplyPatch(original, original, ['parts_request', 'cart'], expected), { parts_request: true });
  assert.deepEqual(casApplyPatch(original, expected, ['parts_request', 'cart'], expected), {});
  assert.throws(() => casApplyPatch(original, { parts_request: false, cart: true }, ['parts_request', 'cart'], expected), /changed during resume/u);
});

test('legacy section-page reconciliation requires exact owned probe identity and known old row shape', () => {
  const suffix = id.slice(0, 8), expected = { id, slug: `acceptance-${suffix}-section-probe`, title: 'Synthetic section transaction probe', status: 'published' };
  const actual = { id, slug: `acceptance-${suffix}-page`, title: 'Synthetic acceptance page', status: 'published' };
  assert.deepEqual(reconcileLegacySectionPage(expected, actual, id, id, [id]), actual);
  assert.equal(reconcileLegacySectionPage(expected, { ...actual, title: 'Edited title' }, id, id, [id]), null);
  assert.equal(reconcileLegacySectionPage(expected, actual, id, id, []), null);
});

test('cleanup diagnostics expose a reason code without leaking raw API details', () => {
  const raw = 'DELETE /users failed: HTTP 400 {"errors":[{"message":"token super-secret","extensions":{"code":"FAILED_VALIDATION"}}]}';
  assert.equal(cleanupReason(new Error(raw)), 'HTTP_400');
  assert.equal(cleanupReason(new Error('wrapped {"errors":[{"extensions":{"code":"FORBIDDEN"}}]}')), 'FORBIDDEN');
  assert.equal(cleanupReason(new Error('sensitive detail')), 'REQUEST_FAILED');
});

test('analog keys are stable for symmetric and directional relation types', () => {
  assert.equal(productAnalogKey('b', 'a', 'analog'), productAnalogKey('a', 'b', 'analog'));
  assert.notEqual(productAnalogKey('b', 'a', 'superseded_by'), productAnalogKey('a', 'b', 'superseded_by'));
});

test('owned child cleanup uses guarded mutations while navigation stays on native REST', () => {
  const request = guardedDeleteRequest('page_sections', id);
  assert.equal(request.path, `/commerce/mutations/page_sections/${id}`);
  assert.deepEqual(JSON.parse(request.options.body), { expected: { id }, action: 'delete' });
  assert.throws(() => guardedDeleteRequest('navigation_items', id), /unguarded/u);
  assert.equal(guardedDeleteRequest('home_page', id, { id, h1: 'Synthetic' }).path, `/commerce/mutations/home_page/${id}`);
  assert.throws(() => guardedDeleteRequest('directus_users', id), /unguarded/u);
});
