import { demoContent } from "../../profiles/commerce/demo-content.mjs";

const field = (name, type, options = {}) => ({ name, type, ...options });

const id = () =>
  field("id", "uuid", {
    primary: true,
    required: true,
    default: "uuid",
    readonly: true,
    hidden: true,
  });

const publicationStatus = () =>
  field("status", "string", {
    required: true,
    default: "draft",
    choices: ["draft", "published", "archived"],
    index: true,
  });

const timestamps = () => [
  field("created_at", "timestamp", {
    special: ["date-created"],
    readonly: true,
    hidden: true,
  }),
  field("updated_at", "timestamp", {
    special: ["date-updated"],
    readonly: true,
    hidden: true,
  }),
];

const contentFields = (...fields) => [
  id(),
  publicationStatus(),
  ...fields,
  ...timestamps(),
];

const translations = () =>
  field("translations", "json", {
    note: "Future translations keyed by locale, for example ru-RU.",
  });

/**
 * R11 additive JSON field of the vendored @directus-labs/seo-plugin 1.1.1
 * (directus/extensions/directus-labs-seo-plugin). PURELY ADDITIVE: nullable,
 * default null, no relation. The frontend reads it JSON-first with the legacy
 * scalar SEO fields as per-key fallback; the scalars stay untouched read-only
 * sources until a separate cleanup release.
 */
const seoPluginField = () =>
  field("seo", "json", {
    interface: "seo-interface",
    display: "seo-display",
    note: "R11 SEO-plugin JSON (title, meta_description, og_image, additional_fields.canonical_url, no_index, no_follow). JSON-first on the frontend; the scalar SEO fields stay the fallback and are never cleared by the migration.",
  });

export const schemaBlueprint = {
  version: 3,
  collections: [
    { name: "group_site", folder: true, icon: "web", sort: 1, fields: [] },
    { name: "group_catalog", folder: true, icon: "inventory_2", sort: 2, fields: [] },
    { name: "group_content", folder: true, icon: "article", sort: 3, fields: [] },
    { name: "group_sales", folder: true, icon: "request_quote", sort: 4, fields: [] },
    { name: "group_settings", folder: true, icon: "settings", sort: 5, fields: [] },
    { name: "group_seo", folder: true, icon: "travel_explore", sort: 6, fields: [] },
    {
      name: "site_settings",
      icon: "settings",
      singleton: true,
      fields: [
        id(),
        field("company_name", "string", { required: true }),
        field("phone", "string", { required: true }),
        field("email", "string", { required: true }),
        field("messengers", "json"),
        field("social_links", "json"),
        field("commerce_profile", "json"),
        field("address", "text"),
        field("city", "string"),
        field("working_hours", "string"),
        field("delivery_region", "string"),
        field("logo", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("favicon", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("default_og_image", "uuid", {
          relatedCollection: "directus_files",
        }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_title", "string"),
        field("og_description", "text"),
        field("primary_color", "string", { default: "#2563eb" }),
        field("accent_color", "string", { default: "#f59e0b" }),
        field("primary_cta_text", "string"),
        field("primary_cta_url", "string"),
        field("footer_text", "text"),
        field("footer_disclaimer", "text"),
        field("inn", "string"),
        field("kpp", "string"),
        field("ogrn", "string"),
        field("legal_address", "text"),
        field("legal_name", "string"),
        field("vat_info", "string"),
        field("requisites_url", "string"),
        field("documents_url", "string"),
        field("company_image", "uuid", { relatedCollection: "directus_files" }),
        field("yandex_metrica_id", "string"),
        field("gtm_id", "string"),
        translations(),
        ...timestamps(),
      ],
    },
    {
      name: "home_page",
      icon: "home",
      singleton: true,
      // Native Directus content versions back the guarded page-builder CAS
      // endpoints. Keep this opt-in so unrelated collections retain their
      // existing versioning metadata.
      versioning: true,
      fields: contentFields(
        field("source_page", "uuid", {
          required: true,
          relatedCollection: "pages",
          index: true,
        }),
        field("h1", "string", { required: true }),
        field("hero_title", "string", { required: true }),
        field("hero_text", "text", { required: true }),
        field("hero_image", "uuid", {
          required: true,
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("hero_image_alt", "string", { required: true }),
        field("hero_primary_button_text", "string"),
        field("hero_primary_button_url", "string"),
        field("hero_secondary_button_text", "string"),
        field("hero_secondary_button_url", "string"),
        field("hero_search_label", "string", { required: true }),
        field("hero_search_placeholder", "string", { required: true }),
        field("hero_search_button_text", "string", { required: true }),
        field("hero_bulk_prompt", "string", { required: true }),
        field("hero_bulk_link_text", "string", { required: true }),
        field("hero_bulk_link_url", "string", { required: true }),
        field("hero_excel_link_text", "string", { required: true }),
        field("hero_excel_link_url", "string", { required: true }),
        field("hero_photo_link_text", "string", { required: true }),
        field("hero_photo_link_url", "string", { required: true }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("canonical_url", "text"),
        field("og_title", "string"),
        field("og_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("is_indexable", "boolean", { default: true }),
        seoPluginField(),
        field("sections", "alias", {
          interface: "list-o2m",
          special: ["o2m"],
        }),
        translations(),
      ),
    },
    {
      name: "pages",
      icon: "web",
      // Native Directus content versions back the guarded page-builder CAS
      // endpoints. Keep this opt-in so unrelated collections retain their
      // existing versioning metadata.
      versioning: true,
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("page_type", "string", {
          required: true,
          choices: [
            "home",
            "catalog",
            "about",
            "delivery",
            "contacts",
            "privacy_policy",
            "thank_you",
            "articles",
            "standard",
          ],
          index: true,
        }),
        field("h1", "string", { required: true }),
        field("eyebrow", "string"),
        field("intro", "text"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("seo_text", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("canonical_url", "text"),
        field("is_indexable", "boolean", { default: true }),
        seoPluginField(),
        translations(),
      ),
    },
    {
      name: "page_sections",
      icon: "view_quilt",
      fields: contentFields(
        field("home_page", "uuid", {
          relatedCollection: "home_page",
          oneField: "sections",
          index: true,
        }),
        field("page", "uuid", {
          relatedCollection: "pages",
          index: true,
          onDelete: "CASCADE",
        }),
        field("section_type", "string", {
          required: true,
          choices: [
            "hero",
            "categories",
            "company_trust",
            "featured_products",
            "advantages",
            "steps",
            "cta",
            "catalog_preview",
            "seo_text",
            "lead_form",
            "parts_request",
            "recent_supplies",
            "faq",
            "contacts",
            "articles",
            "custom",
          ],
          index: true,
        }),
        field("title", "string"),
        field("subtitle", "string"),
        field("text", "text"),
        field("image", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("image_alt", "string"),
        field("button_text", "string"),
        field("button_url", "string"),
        field("items", "json"),
        field("settings", "json"),
        field("is_visible", "boolean", { default: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "navigation_items",
      icon: "menu",
      fields: contentFields(
        field("label", "string", { required: true }),
        field("url", "string", { required: true }),
        field("parent", "uuid", {
          relatedCollection: "navigation_items",
        }),
        field("location", "string", {
          required: true,
          default: "header",
          choices: ["header", "footer", "legal"],
          index: true,
        }),
        field("open_in_new_tab", "boolean", { default: false }),
        field("is_visible", "boolean", { default: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "categories",
      icon: "category",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("parent", "uuid", { relatedCollection: "categories" }),
        field("description", "text"),
        field("image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("icon", "uuid", { relatedCollection: "directus_files" }),
        field("icon_alt", "string"),
        field("h1", "string"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("seo_text", "text"),
        field("intro", "text"),
        field("selection_guide", "json"),
        field("internal_links", "json"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("faq", "json"),
        field("is_indexable", "boolean", { default: true, index: true }),
        seoPluginField(),
        field("redirect_target", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        field("show_on_homepage", "boolean", { default: false }),
        translations(),
      ),
    },
    {
      name: "articles",
      icon: "article",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("excerpt", "text", { required: true }),
        field("content", "text", {
          required: true,
          interface: "input-rich-text-html",
        }),
        field("content_blocks", "json", {
          special: ["cast-json"],
          interface: "flexible-editor",
          options: {
            m2aField: "editor_nodes",
            relationBlocks: ["products", "categories"],
            relationInlineBlocks: ["products", "categories"],
            relationMarks: ["products", "categories"],
            tools: [
              "paragraph",
              "h2",
              "h3",
              "h4",
              "bold",
              "italic",
              "strike",
              "underline",
              "code",
              "subscript",
              "superscript",
              "link",
              "removeLink",
              "autolink",
              "bulletList",
              "orderedList",
              "blockquote",
              "codeBlock",
              "table",
              "horizontalRule",
              "hardBreak",
              "textAlign",
              "undo",
              "redo",
            ],
          },
          note: "Structured ProseMirror content of the flexible editor. articles.content (HTML) stays the canonical source until the cutover release.",
        }),
        field("editor_nodes", "alias", {
          special: ["m2a"],
          interface: null,
          hidden: true,
          relatedCollection: "articles_editor_nodes",
          note: "Hidden M2A alias managed by the flexible editor. Related collections: products, categories.",
        }),
        field("cover_image", "uuid", {
          relatedCollection: "directus_files",
        }),
        field("image_alt", "string"),
        field("published_at", "timestamp", { required: true, index: true }),
        field("category_label", "string"),
        field("reading_time_minutes", "integer"),
        field("author", "string"),
        field("reviewer", "string"),
        field("sources", "json"),
        field("related_categories", "json"),
        field("related_products", "json"),
        field("is_featured", "boolean", { default: false, index: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        seoPluginField(),
        translations(),
      ),
    },
    {
      name: "articles_editor_nodes",
      icon: "account_tree",
      hidden: true,
      note: "M2A junction of the articles flexible editor (articles.editor_nodes). Created before the alias; managed by the editor, not by hand.",
      fields: [
        id(),
        field("articles_id", "uuid", {
          required: true,
          relatedCollection: "articles",
          oneField: "editor_nodes",
          index: true,
          onDelete: "CASCADE",
        }),
        field("collection", "alias", {
          special: ["m2a"],
          note: "Polymorphic discriminator of the related collection (products or categories). Alias — matches the live schema created by the R7 migration.",
        }),
        field("item", "uuid", {
          special: ["m2o"],
          junctionField: "collection",
          note: "Polymorphic key of the related item. Column (the R7 migration created it with a real column; only the discriminator is an alias).",
        }),
      ],
    },
    {
      name: "products",
      icon: "inventory_2",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("sku", "string", {
          required: true,
          identityManagedUnique: true,
          index: true,
        }),
        field("category", "uuid", {
          relatedCollection: "categories",
          index: true,
        }),
        field("short_description", "text"),
        field("full_description", "text"),
        field("seo_text", "text"),
        field("main_image", "uuid", { relatedCollection: "directus_files" }),
        field("gallery", "json"),
        field("media_sources", "json", {
          hidden: true,
          readonly: true,
          note: "Managed source policy per images/specifications/documents: children or legacy. Empty children do not restore legacy data.",
        }),
        field("price", "decimal", { precision: 12, scale: 2 }),
        field("currency", "string", { required: true, default: "RUB" }),
        field("price_status", "string", {
          required: true,
          default: "fixed",
          choices: ["fixed", "on_request", "hidden"],
          index: true,
        }),
        field("availability_status", "string", {
          required: true,
          default: "on_request",
          choices: ["in_stock", "on_request", "out_of_stock"],
          index: true,
        }),
        field("brand", "string"),
        field("brand_key", "string", {
          hidden: true,
          readonly: true,
          index: true,
          note: "Server-owned normalized brand label; original brand remains unchanged.",
        }),
        field("identity_key", "string", {
          unique: true,
          maxLength: 64,
          hidden: true,
          readonly: true,
          note: "SHA256 of normalized brand and article. Backfill and constraint cutover require migrate-product-identity.mjs; no automatic brand aliasing.",
        }),
        field("mpn", "string", { index: true }),
        field("gtin", "string", { index: true }),
        field("sku_normalized", "string", {
          hidden: true,
          index: true,
          note: "Derived uppercase alphanumeric copy of sku, filled only by migrations/backfill-product-search.mjs. Indexed search key, never edited by hand.",
        }),
        field("mpn_normalized", "string", {
          hidden: true,
          index: true,
          note: "Derived uppercase alphanumeric copy of mpn, filled only by migrations/backfill-product-search.mjs. Indexed search key, never edited by hand.",
        }),
        field("part_type", "string", {
          choices: ["original", "oem", "analog"],
        }),
        field("delivery_status", "string"),
        field("specifications", "json"),
        field("documents", "json"),
        // R7C DECLARATION ONLY — not applied in the R7A/R7B releases. Alias
        // fields have no DB column (schema: null in apply-schema), so a
        // future schema:apply creates metadata only. The legacy JSON fields
        // above keep their list interfaces until the gated R7C cutover.
        field("image_items", "alias", {
          special: ["o2m"],
          interface: null,
          hidden: true,
          relatedCollection: "product_images",
          note: "R7C declaration: hidden O2M alias over product_images. products.gallery JSON stays the editable interface until the R7C gate (after the R7B gallery migration and reconcile).",
        }),
        field("specification_items", "alias", {
          special: ["o2m"],
          interface: null,
          hidden: true,
          relatedCollection: "product_specifications",
          note: "R7C declaration: hidden O2M alias over product_specifications. products.specifications JSON stays the editable interface until the R7C gate.",
        }),
        field("document_items", "alias", {
          special: ["o2m"],
          interface: null,
          hidden: true,
          relatedCollection: "product_documents",
          note: "R7C declaration: hidden O2M alias over product_documents. products.documents JSON stays the editable interface until the R7C gate.",
        }),
        // R8 DECLARATION — hidden O2M aliases over products_analogs. Alias
        // fields have no DB column and are never posted as relation sides:
        // the junction-side M2Os below carry one_field and register them.
        // Edits happen in the products_analogs collection, not on the form.
        field("analogs_from", "alias", {
          special: ["o2m"],
          interface: null,
          hidden: true,
          relatedCollection: "products_analogs",
          note: "R8 declaration: hidden O2M alias over products_analogs.product_from (edges stored with this product as the from side). Manage edges in the products_analogs collection.",
        }),
        field("analogs_to", "alias", {
          special: ["o2m"],
          interface: null,
          hidden: true,
          relatedCollection: "products_analogs",
          note: "R8 declaration: hidden O2M alias over products_analogs.product_to (edges stored with this product as the to side). Manage edges in the products_analogs collection.",
        }),
        field("source_name", "string"),
        field("source_url", "string"),
        field("verified_at", "timestamp"),
        field("reviewed_by", "string"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("seo_quality_status", "string", {
          default: "pending",
          choices: ["pending", "reviewed", "published", "needs_fix"],
          index: true,
        }),
        field("is_indexable", "boolean", { default: true, index: true }),
        seoPluginField(),
        field("sort_order", "integer", { default: 0, index: true }),
        field("popularity_score", "integer", { default: 0, index: true }),
        field("is_featured", "boolean", { default: false, index: true }),
        field("show_on_homepage", "boolean", {
          default: false,
          index: true,
        }),
        field("cta_text", "string"),
        field("related_products", "json"),
        field("lead_form", "uuid", { relatedCollection: "lead_forms" }),
        translations(),
      ),
    },
    {
      name: "faq_items",
      icon: "quiz",
      fields: contentFields(
        field("question", "string", { required: true }),
        field("answer", "text", { required: true }),
        field("page", "uuid", { relatedCollection: "pages" }),
        field("category", "uuid", { relatedCollection: "categories" }),
        field("product", "uuid", { relatedCollection: "products" }),
        field("sort_order", "integer", { default: 0 }),
        field("is_visible", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "lead_forms",
      icon: "dynamic_form",
      fields: contentFields(
        field("code", "string", { required: true, unique: true, index: true }),
        field("title", "string", { required: true }),
        field("description", "text"),
        field("button_text", "string"),
        field("success_message", "text"),
        field("success_url", "string", { default: "/thank-you" }),
        field("fields", "json"),
        field("turnstile_required", "boolean", { default: true }),
        field("is_active", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "leads",
      icon: "inbox",
      fields: [
        id(),
        field("request_key", "uuid", { unique: true, hidden: true, readonly: true }),
        field("request_fingerprint", "string", { maxLength: 64, hidden: true, readonly: true }),
        field("user_created", "uuid", { relatedCollection: "directus_users", special: ["user-created"], hidden: true, readonly: true }),
        field("status", "string", {
          required: true,
          default: "new",
          choices: ["new", "in_progress", "closed", "spam"],
          index: true,
        }),
        field("name", "string"),
        field("phone", "string", { relaxNullable: true }),
        field("email", "string"),
        field("message", "text"),
        field("product", "uuid", { relatedCollection: "products" }),
        field("category", "uuid", { relatedCollection: "categories" }),
        field("lead_form", "uuid", { relatedCollection: "lead_forms" }),
        field("page_url", "text", { required: true }),
        field("utm_source", "string"),
        field("utm_medium", "string"),
        field("utm_campaign", "string"),
        field("utm_content", "string"),
        field("utm_term", "string"),
        field("request_items", "json", {
          note: "Normalized parts request lines: article and quantity.",
        }),
        field("attachments", "json", {
          note: "Directus file IDs uploaded with a parts request.",
        }),
        field("marketing_consent", "boolean", { default: false }),
        field("marketing_consent_at", "timestamp"),
        field("marketing_consent_version", "string"),
        field("manager_comment", "text"),
        ...timestamps(),
      ],
    },
    {
      name: "contact_channels",
      icon: "contact_phone",
      fields: contentFields(
        field("page_section", "uuid", {
          relatedCollection: "page_sections",
          index: true,
        }),
        field("channel_type", "string", {
          required: true,
          choices: ["phone", "email", "messenger", "address", "hours"],
          index: true,
        }),
        field("label", "string", { required: true }),
        field("value", "string", { required: true }),
        field("url", "string"),
        field("icon", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        field("is_visible", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "recent_supplies",
      icon: "local_shipping",
      fields: contentFields(
        field("image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("equipment_type", "string"),
        field("positions", "json"),
        field("region", "string"),
        field("delivery_term", "string"),
        field("supply_format", "string"),
        field("supplied_at", "timestamp", { index: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_images",
      icon: "photo_library",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          oneField: "image_items",
          index: true,
          onDelete: "CASCADE",
        }),
        field("image", "uuid", {
          required: true,
          relatedCollection: "directus_files",
        }),
        field("alt_text", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_specifications",
      icon: "table_chart",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          oneField: "specification_items",
          index: true,
          onDelete: "CASCADE",
        }),
        field("group_name", "string"),
        field("name", "string", { required: true }),
        field("value", "string", { required: true }),
        field("unit", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_documents",
      icon: "description",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          oneField: "document_items",
          index: true,
          onDelete: "CASCADE",
        }),
        field("file", "uuid", {
          required: true,
          relatedCollection: "directus_files",
        }),
        field("title", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_codes",
      icon: "qr_code_2",
      note: "Additional OEM/MPN/supplier/previous/superseded/external/barcode codes of a product (ADR-003); products.sku and products.mpn stay the canonical article fields. The composite UNIQUE (product, code_type, normalized_code, source_name) is created by migrations/sql/product-search-indexes-up.sql — the Directus REST API cannot express composite constraints.",
      fields: [
        id(),
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          index: true,
          onDelete: "CASCADE",
        }),
        field("code", "string", { required: true }),
        field("normalized_code", "string", {
          required: true,
          index: true,
          note: "Uppercase alphanumeric copy of code: the indexed OEM search key.",
        }),
        field("code_type", "string", {
          required: true,
          default: "oem",
          choices: [
            "oem",
            "mpn",
            "supplier",
            "previous",
            "superseded",
            "external",
            "barcode",
          ],
          index: true,
        }),
        field("source_name", "string", {
          required: true,
          default: "manual",
          index: true,
          note: "Provenance of the code (feed or catalog name, 'manual' for editors).",
        }),
        field("source_reference", "string"),
        field("is_active", "boolean", { default: true, index: true }),
        ...timestamps(),
      ],
    },
    {
      name: "products_analogs",
      icon: "compare_arrows",
      note: "Typed one-edge relations between products (R8, ADR-003): analog/oem_cross/compatible are symmetric — canonical_key derives from the SORTED id pair so a mirror duplicate is physically impossible under the unique key; superseded_by is directed and keeps the from/to order. No self-edges (CHECK) and UNIQUE canonical_key are enforced by migrations/sql/product-analogs-constraints-up.sql — the Directus REST API cannot express table CHECKs.",
      fields: [
        id(),
        field("product_from", "uuid", {
          required: true,
          relatedCollection: "products",
          oneField: "analogs_from",
          index: true,
          onDelete: "CASCADE",
        }),
        field("product_to", "uuid", {
          required: true,
          relatedCollection: "products",
          oneField: "analogs_to",
          index: true,
          onDelete: "CASCADE",
        }),
        field("relation_type", "string", {
          required: true,
          choices: ["analog", "oem_cross", "compatible", "superseded_by"],
          index: true,
        }),
        field("canonical_key", "string", {
          required: true,
          index: true,
          note: "Deterministic edge key '<type>:<from>:<to>': the pair is SORTED for the symmetric types and the direction preserved for superseded_by. Physically UNIQUE via migrations/sql/product-analogs-constraints-up.sql; recomputed and verified by migrations/reconcile-product-analogs.mjs.",
        }),
        field("source_name", "string", {
          required: true,
          default: "manual",
          index: true,
          note: "Provenance of the relation (feed or catalog name, 'manual' for editors).",
        }),
        field("note", "text"),
        field("verified_at", "timestamp"),
        ...timestamps(),
      ],
    },
    {
      name: "seo_redirects",
      icon: "alt_route",
      fields: [
        id(),
        field("old_url", "string", { required: true, unique: true, index: true }),
        field("new_url", "string", { required: true }),
        field("status_code", "integer", {
          required: true,
          default: 301,
          choices: [301, 302],
        }),
        field("is_active", "boolean", { default: true, index: true }),
        ...timestamps(),
      ],
    },
    {
      name: "seo_work_items",
      icon: "checklist",
      note: "Control-plane queue of the SEO content factory (R10A, Task 14): one row per worker recommendation with evidence, sources and a draft-only patch. The W1 worker only ever writes status=draft; ready/review/applied/rolled_back/rejected are human lifecycle transitions. status is Directus choices, NOT a SQL enum. dedupe_key (sha256 of entity+type+subtype+patch) is physically UNIQUE via migrations/sql/seo-work-items-constraints-up.sql — the Directus REST API cannot express the constraint without creating a duplicate of its own. High-volume crawl telemetry is never written here.",
      fields: [
        id(),
        field("type", "string", {
          index: true,
          note: "Recommendation type, for example missing_meta or title_rewrite.",
        }),
        field("subtype", "string", {
          index: true,
          note: "Optional refinement of type.",
        }),
        field("status", "string", {
          required: true,
          default: "draft",
          choices: ["draft", "ready", "review", "approved", "processing", "draft_created", "retryable", "applied", "rolled_back", "rejected"],
          index: true,
        }),
        field("severity", "string", {
          default: "minor",
          index: true,
          note: "Impact label of the recommendation (minor/major/...).",
        }),
        field("priority_score", "integer", { default: 0, index: true }),
        field("confidence", "decimal", {
          precision: 5,
          scale: 4,
          default: 0,
          note: "Model/analysis confidence 0..1.",
        }),
        field("entity_type", "string", {
          index: true,
          note: "Target collection of the recommendation: articles, categories, products, pages or home_page.",
        }),
        field("entity_id", "uuid"),
        field("entity_key", "string", {
          index: true,
          note: "Stable human key of the target (slug/sku) — survives re-imports that change entity_id.",
        }),
        field("url", "string"),
        field("title", "string"),
        field("summary", "text"),
        field("recommendation", "text"),
        field("current_value_json", "json", {
          note: "Snapshot of the target field values at analysis time.",
        }),
        field("proposed_value_json", "json"),
        field("patch_json", "json", {
          note: "Allowlisted field patch the worker proposes; applied only after human approval.",
        }),
        field("evidence_json", "json", {
          note: "Claim-to-source evidence tiers backing the recommendation.",
        }),
        field("sources_json", "json"),
        field("metrics_json", "json", {
          note: "Compact decision metrics only — crawl telemetry lives outside this collection.",
        }),
        field("dedupe_key", "string", {
          required: true,
          index: true,
          note: "Deterministic sha256 of entity_type+entity_key+type+subtype+patch (seo-worker computeDedupeKey). Physically UNIQUE via migrations/sql/seo-work-items-constraints-up.sql, the product_codes/analogs precedent.",
        }),
        field("before_hash", "string", {
          note: "sha256 of the target field values at analysis time; a mismatch means the entity changed and the proposal is stale.",
        }),
        field("article", "uuid", {
          relatedCollection: "articles",
          index: true,
          note: "Nullable M2O to the draft article created from an approved work item. Junction side only — articles carries no O2M alias (production R7 lesson).",
        }),
        field("worker_run_id", "string", {
          index: true,
          note: "Run identifier of the W1 worker that produced or claimed the item.",
        }),
        field("claimed_at", "timestamp", {
          note: "When a worker run claimed the item for execution.",
        }),
        field("expires_at", "timestamp", {
          index: true,
          note: "Claim expiry; an expired claim may be taken over by another run.",
        }),
        field("applied_at", "timestamp"),
        field("rolled_back_at", "timestamp"),
        field("last_error", "text"),
        ...timestamps(),
      ],
    },
    {
      name: "orders",
      icon: "shopping_cart_checkout",
      fields: [
        id(),
        field("user_created", "uuid", { relatedCollection: "directus_users", special: ["user-created"], hidden: true, readonly: true }),
        field("status", "string", {
          required: true,
          default: "new",
          choices: [
            "new",
            "in_progress",
            "confirmed",
            "shipped",
            "delivered",
            "cancelled",
          ],
          index: true,
        }),
        field("request_key", "uuid", { unique: true, index: true, hidden: true, readonly: true, note: "Durable first-party request identity. Nullable only for legacy orders." }),
        field("request_fingerprint", "string", { hidden: true, readonly: true }),
        field("customer_name", "string", { required: true }),
        field("phone", "string", { required: true }),
        field("email", "string"),
        field("comment", "text"),
        field("total", "decimal", { precision: 12, scale: 2 }),
        field("currency", "string", { required: true, default: "RUB" }),
        field("page_url", "text", { required: true }),
        field("utm_source", "string"),
        field("utm_medium", "string"),
        field("utm_campaign", "string"),
        field("utm_content", "string"),
        field("utm_term", "string"),
        field("marketing_consent", "boolean", { default: false }),
        field("marketing_consent_at", "timestamp"),
        field("marketing_consent_version", "string"),
        field("manager_comment", "text"),
        ...timestamps(),
      ],
    },
    {
      name: "order_items",
      icon: "inventory",
      note: "Snapshot line items for an order. order→products is SET NULL on product deletion to preserve history.",
      fields: [
        id(),
        field("order", "uuid", {
          required: true,
          relatedCollection: "orders",
          index: true,
          onDelete: "CASCADE",
        }),
        field("product", "uuid", {
          relatedCollection: "products",
          index: true,
        }),
        field("sku_snapshot", "string"),
        field("title_snapshot", "text"),
        field("brand_snapshot", "string"),
        field("unit_price", "decimal", { precision: 12, scale: 2 }),
        field("quantity", "integer", { required: true, default: 1 }),
        field("currency", "string", { required: true, default: "RUB" }),
        ...timestamps(),
      ],
    },
  ],
  seed: demoContent,
};
